### ISSUE TITLE
What version of sklearn did you use for this project? And could you show us the code to generate stratifiedKFold.query.pkl  stratifiedKFold.relevance.pkl ?

### ISSUE THREAD

**Issue by hcwang95** [ChenglongChen/Kaggle_CrowdFlower#3]
Hi, I am trying to reproduce your solution, but the following error was raised when I executed

python3 getFeat_id_feat.py

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
==================================================
Generate id features...
For cross-validation...
Traceback (most recent call last):
  File "genFeat_id_feat.py", line 56, in <module>
    for fold, (validInd, trainInd) in enumerate(skf[run]):
  File "/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py", line 82, in __iter__
    ind = np.arange(self.n)
AttributeError: 'StratifiedKFold' object has no attribute 'n'

So it should be the issue of depreciation of the attribute. I am wondering if you could help me by showing the code to generate stratifiedKFold.query.pkl  stratifiedKFold.relevance.pkl this two files.

Thanks!

**Comment by ChenglongChen** [comment]
Please see the file [gen_kfold.py](https://github.com/ChenglongChen/Kaggle_CrowdFlower/blob/master/Code/Feat/gen_kfold.py) for how I generated the indices in stratifiedKFold.query.pkl and stratifiedKFold.relevance.pkl. FYI, I used python 2.7.8 and sklearn 0.16.1 as detailed in the dependencies part in the documentation.

**Comment by hcwang95** [comment]
Sure, I will try to modify it. Thanks
